import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk } from 'next/font/google'
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper";
import TokenDebugger from "./components/DebugAuth";
import RedirectDebugger from "./components/DebugAuth";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={spaceGrotesk.className}
      >
        <div className='bg-white h-[100%]'>
          <LayoutWrapper>
          <RedirectDebugger/>
          <Providers>
            <Toaster 
  position="top-right"
  toastOptions={{
    duration: 4000,
    style: {
      background: '#363636',
      color: '#fff',
    },
    success: {
      duration: 3000,
      style: {
        background: '#22c55e', // Green color
        color: '#fff',
      },
    },
    error: {
      duration: 4000,
      style: {
        background: '#ef4444', // Red color
        color: '#fff',
      },
    },
  }}
/>
        {children}
        </Providers>
        </LayoutWrapper>
        </div>
      </body>
    </html>
  );
}
